name: check package

on:
  workflow_call:
    inputs:
      php:
        default: '["8.1"]'
        required: true
        type: string
      laravel:
        default: '["10.*"]'
        required: false
        type: string
      dependencyVersion:
        default: '["prefer-stable"]'
        required: false
        type: string
    secrets:
      composerAuthJson:
        required: true

jobs:
  check_package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJSON(inputs.php) }}
        laravel: ${{ fromJSON(inputs.laravel) }}
        dependency-version: ${{ fromJSON(inputs.dependencyVersion) }}
        include:
          - laravel: 11.*
            testbench: 9.*
          - laravel: 10.*
            testbench: 8.*
        exclude:
          - laravel: 11.*
            php: 8.1
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ github.event.repository.full_name }}-${{ matrix.laravel }}-php-${{ matrix.php }}-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, pdo, pdo_mysql, redis, json, dom, curl, libxml
          coverage: xdebug

      - name: Write composer auth config
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: auth.json
          contents: ${{ secrets.composerAuthJson }}
          write-mode: overwrite

      - name: Add Laramity composer repository
        run: composer config repositories.laramity composer https://packagist.laramity.com

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Run GrumPHP tasks
        run: ./vendor/bin/grumphp run --no-interaction --tasks=phplint,phpstan

      - name: Execute tests
        run: ./vendor/bin/pest --coverage
